[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
airdr0ppy = "Gj9YNmzd7TXso7J1bvMvvvFPSn6cqooqh53dkuee6MUy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
